import { getCollectionSnapshots, getInventoryStatusCounts } from "./calculations.js";
import {
  getCapitalAdded,
  getCapitalDeployed,
  getCapitalRecoverySummary,
  getCashAvailable,
  getCOGS,
  getCollectionBusinessMetrics,
  getExpectedProfitLeft,
  getExpectedSalesLeft,
  getExpenseSummary,
  getGrossProfit,
  getPlatformRows,
  getRevenue,
  getSalesSummary,
  getTotalExpenses,
} from "./financials.js";

export function buildFullBusinessReportRows(store, filters = {}) {
  const sales = getSalesSummary(store, filters);
  const expenses = getExpenseSummary(store, filters);
  const collections = getCollectionSnapshots(store, filters);
  const collectionBusiness = getCollectionBusinessMetrics(store, filters);
  const platforms = getPlatformRows(store, filters);
  const inventoryStatus = getInventoryStatusCounts(store.inventory);
  const recovery = getCapitalRecoverySummary(store, { startDate: null, endDate: null });

  return [
    ["Nana Kollects Full Business Report"],
    ["Generated At", new Date().toISOString()],
    [],
    ["Profit Summary"],
    ["Sales Collected", getRevenue(store, filters)],
    ["COGS", getCOGS(store, filters)],
    ["Profit", getGrossProfit(store, filters)],
    ["Expenses", getTotalExpenses(store, filters)],
    ["Cash Available", getCashAvailable(store)],
    ["Inventory Capital", getCapitalDeployed(store)],
    ["Total Inventory Cost", recovery.totalInventoryCost],
    ["Sales Collected So Far", recovery.salesCollected],
    ["Capital Recovery Rate", `${recovery.recoveryRate}%`],
    ["Potential Sales", getExpectedSalesLeft(store)],
    ["Expected Final Revenue", getRevenue(store, filters) + getExpectedSalesLeft(store)],
    ["Projected Profit", getRevenue(store, filters) + getExpectedSalesLeft(store) - recovery.totalInventoryCost],
    ["Expected Profit Left", getExpectedProfitLeft(store)],
    [],
    ["Sales Summary"],
    ["Sales", sales.orders],
    ["Avg Order Value", sales.averageOrderValue],
    ["Profit Margin", `${sales.profitMargin}%`],
    [],
    ["Inventory Summary"],
    ["Inventory Items", store.inventory.length],
    ["Sales Value of Active Inventory", getExpectedSalesLeft(store)],
    ["Inventory Capital", getCapitalDeployed(store)],
    [],
    ["Inventory Status Summary"],
    ["Available", inventoryStatus.available],
    ["Reserved", inventoryStatus.reserved],
    ["Sold Stock", inventoryStatus.sold],
    ["Written Off", inventoryStatus.writtenOff],
    ["Archived", inventoryStatus.archived],
    [],
    ["Capital Summary"],
    ["Capital Added", getCapitalAdded(store)],
    ["Cash Available", getCashAvailable(store)],
    [],
    ["Expenses Summary"],
    ["Total Expenses", expenses.totalExpenses],
    ["Write-Offs", expenses.writeOffExpenses],
    ["Operating Expenses", expenses.operatingExpenses],
    [],
    ["Collections Summary"],
    ["Collection", "Items", "Sold Stock", "Left", "Sales Collected", "Profit", "ROI"],
    ...collections.map((collection) => [
      collection.name,
      collection.itemsCount,
      collection.soldCount,
      collection.remainingCount,
      collection.revenue,
      collection.profit,
      `${Math.round(collection.roi * 10) / 10}%`,
    ]),
    [],
    ["Collection Business Metrics"],
    ["Collection", "Total Inventory Cost", "Sales Collected", "Recovery Rate", "Potential Sales", "Expected Final Revenue", "Projected Profit", "Sold Stock", "Items Left"],
    ...collectionBusiness.map((collection) => [
      collection.name,
      collection.totalInventoryCost,
      collection.salesCollected,
      `${collection.recoveryRate}%`,
      collection.inventoryLeftValue,
      collection.expectedFinalRevenue,
      collection.expectedGrossProfit,
      collection.soldStock,
      collection.itemsLeft,
    ]),
    [],
    ["Platform Summary"],
    ["Platform", "Sales", "Sales Collected", "Profit", "Sales Share", "Avg Profit / Sale"],
    ...platforms.map((platform) => [
      platform.platform,
      platform.orders,
      platform.revenue,
      platform.profit,
      `${platform.revenueShare}%`,
      platform.averageProfitPerSale,
    ]),
  ];
}
